# Generated by Django 5.1.2 on 2024-10-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_rename_name_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
