# Generated by Django 5.1.2 on 2024-10-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_employee_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
    ]
