# Generated by Django 5.1.2 on 2024-10-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_remove_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
